VV = {
    "mode": "vv",
    "suffix": "vv",
    "instrs": [
        # "vadc_vvm",
        # "vsbc_vvm",
        # "vmerge_vvm",
        "vadd",
        "vsub",
        "vmadc",
        "vmsbc",
        "vand",
        "vor",
        "vxor",
        "vsll",
        "vsrl",
        "vsra",
        "vmseq",
        "vmsne",
        "vmsltu",
        "vmslt",
        "vmsleu",
        "vmsle",
        "vminu",
        "vmin",
        "vmaxu",
        "vmax",
        "vmul",
        "vmulh",
        "vmulhu",
        "vmulhsu",
        "vmacc",
        "vnmsac",
        "vmadd",
        "vnmsub",
        "vsaddu",
        "vsadd",
        "vssubu",
        "vssub",
        "vaaddu",
        "vaadd",
        "vasubu",
        "vasub",
        "vsmul",
        "vssrl",
        "vssra",
    ],
    "lmuls": ["m1", "m2", "m4", "m8"],
    "frac_lmuls": ["mf2", "mf4", "mf8"],
    "widths": [8, 16, 32],
}

VX = {
    "mode": "vx",
    "suffix": "vx",
    "instrs": [
        # "vadc_vvm",
        # "vsbc_vvm",
        # "vmerge_vvm",
        "vadd",
        "vsub",
        "vmadc",
        "vmsbc",
        "vand",
        "vor",
        "vxor",
        "vsll",
        "vsrl",
        "vsra",
        "vmseq",
        "vmsne",
        "vmsltu",
        "vmslt",
        "vmsleu",
        "vmsle",
        "vminu",
        "vmin",
        "vmaxu",
        "vmax",
        "vmul",
        "vmulh",
        "vmulhu",
        "vmulhsu",
        # "vmacc",
        # "vnmsac",
        # "vmadd",
        # "vnmsub",
        "vsaddu",
        "vsadd",
        "vssubu",
        "vssub",
        "vaaddu",
        "vaadd",
        "vasubu",
        "vasub",
        "vsmul",
        "vssrl",
        "vssra",
    ],
    "lmuls": ["m1", "m2", "m4", "m8"],
    "frac_lmuls": ["mf2", "mf4", "mf8"],
    "widths": [8, 16, 32],
}

WVV = {
    "mode": "wvv",
    "suffix": "wvv",
    "instrs": ["vwadd", "vwsub"],
    "lmuls": ["m1", "m2", "m4"],
    "frac_lmuls": ["mf2", "mf4", "mf8"],
    "widths": [8, 16],
}

WWV = {
    "mode": "wwv",
    "suffix": "wwv",
    "instrs": ["vwadd", "vwsub"],
    "lmuls": ["m1", "m2", "m4"],
    "frac_lmuls": ["mf2", "mf4", "mf8"],
    "widths": [8, 16],
}

EXT = {
    "mode": "ext",
    "suffix": "v",
    "instrs": ["vsext", "vzext"],
    "lmuls": ["m1", "m2", "m4"],
    "frac_lmuls": ["mf2", "mf4"],
    "widths": [16, 32],
}

INSTR_TYPES = [VV, VX]

TEST_FUNCS = {
    # 1. Add/Sub
    "vadd": {
        "modes": ["vv", "vx", "vi"],
        "signs": ["i", "u"],
        "lmuls": ["m1", "m2", "m4", "m8"],
        "frac_lmuls": ["mf2", "mf4", "mf8"],
        "widths": [8, 16, 32],
    },
    "vsub": {
        "modes": ["vv", "vx"],
        "signs": ["i", "u"],
        "lmuls": ["m1", "m2", "m4", "m8"],
        "frac_lmuls": ["mf2", "mf4", "mf8"],
        "widths": [8, 16, 32],
    },
    "vrsub": {
        "modes": ["vi", "vx"],
        "signs": ["i", "u"],
        "lmuls": ["m1", "m2", "m4", "m8"],
        "frac_lmuls": ["mf2", "mf4", "mf8"],
        "widths": [8, 16, 32],
    },
    # 2. Widening Add/Sub
    "vwadd": {
        "modes": ["wvv", "wwv", "wvx", "wwx"],
        "signs": ["i"],
        "lmuls": ["m1", "m2", "m4"],
        "frac_lmuls": ["mf2", "mf4", "mf8"],
        "widths": [8, 16],
    },
    "vwsub": {
        "modes": ["wvv", "wwv", "wvx", "wwx"],
        "signs": ["i"],
        "lmuls": ["m1", "m2", "m4"],
        "frac_lmuls": ["mf2", "mf4", "mf8"],
        "widths": [8, 16],
    },
    "vwaddu": {
        "modes": ["wvv", "wwv", "wvx", "wwx"],
        "signs": ["u"],
        "lmuls": ["m1", "m2", "m4"],
        "frac_lmuls": ["mf2", "mf4", "mf8"],
        "widths": [8, 16],
    },
    "vwsubu": {
        "modes": ["wvv", "wwv", "wvx", "wwx"],
        "signs": ["u"],
        "lmuls": ["m1", "m2", "m4"],
        "frac_lmuls": ["mf2", "mf4", "mf8"],
        "widths": [8, 16],
    },
    # 3. Zero/Sign Extension
    "vsext": {
        "modes": ["ext"],
        "signs": ["i"],
        "lmuls": ["m1", "m2", "m4"],
        "frac_lmuls": ["mf2", "mf4"],
        "widths": [16, 32],
    },
    "vzext": {
        "modes": ["ext"],
        "signs": ["u"],
        "lmuls": ["m1", "m2", "m4"],
        "frac_lmuls": ["mf2", "mf4"],
        "widths": [16, 32],
    },
    # 5. Bitwise Logical Instructions
    "vand": {
        "modes": ["vv", "vi", "vx"],
        "signs": ["i", "u"],
        "lmuls": ["m1", "m2", "m4", "m8"],
        "frac_lmuls": ["mf2", "mf4", "mf8"],
        "widths": [8, 16, 32],
    },
    "vor": {
        "modes": ["vv", "vi", "vx"],
        "signs": ["i", "u"],
        "lmuls": ["m1", "m2", "m4", "m8"],
        "frac_lmuls": ["mf2", "mf4", "mf8"],
        "widths": [8, 16, 32],
    },
    "vxor": {
        "modes": ["vv", "vi", "vx"],
        "signs": ["i", "u"],
        "lmuls": ["m1", "m2", "m4", "m8"],
        "frac_lmuls": ["mf2", "mf4", "mf8"],
        "widths": [8, 16, 32],
    },
    "vmul": {
        "modes": ["vv", "vx"],
        "signs": ["i", "u"],
        "lmuls": ["m1", "m2", "m4", "m8"],
        "frac_lmuls": ["mf2", "mf4", "mf8"],
        "widths": [8, 16, 32],
    },
    "vmulh": {
        "modes": ["vv", "vx"],
        "signs": ["i"],
        "lmuls": ["m1", "m2", "m4", "m8"],
        "frac_lmuls": ["mf2", "mf4", "mf8"],
        "widths": [8, 16, 32],
    },
    "vmulhu": {
        "modes": ["vv", "vx"],
        "signs": ["u"],
        "lmuls": ["m1", "m2", "m4", "m8"],
        "frac_lmuls": ["mf2", "mf4", "mf8"],
        "widths": [8, 16, 32],
    },
    # Divide
    "vdiv": {
        "modes": ["vv", "vx"],
        "signs": ["i"],
        "lmuls": ["m1", "m2", "m4", "m8"],
        "frac_lmuls": ["mf2", "mf4", "mf8"],
        "widths": [8, 16, 32],
    },
    "vdivu": {
        "modes": ["vv", "vx"],
        "signs": ["u"],
        "lmuls": ["m1", "m2", "m4", "m8"],
        "frac_lmuls": ["mf2", "mf4", "mf8"],
        "widths": [8, 16, 32],
    },
    "vrem": {
        "modes": ["vv", "vx"],
        "signs": ["i"],
        "lmuls": ["m1", "m2", "m4", "m8"],
        "frac_lmuls": ["mf2", "mf4", "mf8"],
        "widths": [8, 16, 32],
    },
    "vremu": {
        "modes": ["vv", "vx"],
        "signs": ["u"],
        "lmuls": ["m1", "m2", "m4", "m8"],
        "frac_lmuls": ["mf2", "mf4", "mf8"],
        "widths": [8, 16, 32],
    },
    "vcompress": {
        "modes": ["vm"],
        "signs": ["u"],
        "lmuls": ["m1", "m2", "m4", "m8"],
        "frac_lmuls": ["mf2", "mf4", "mf8"],
        "widths": [8, 16, 32],
    },
}
